---
#reference for installation : https://gist.github.com/Burning-Chai/4ba5fc640397169780c1cb3357f2190c
- name: Install jboss app server and its dependencies
  hosts: all
  gather_facts: no
  remote_user: centos
  become: yes
  become_user: root
  become_method: sudo
  vars:
    - welcome_msg: "Welcome to AWS"

  tasks:
    - name: Create base devops directory
      file: path=/devops state=directory mode=777

    - name: Install git, wget, tree, openssl, unzip
      yum: name="{{item}}" state=present
      with_items:
        - git.x86_64
        - wget.x86_64
        - tree.x86_64
        - openssl.x86_64
        - unzip.x86_64
        - java-1.8.0-openjdk.x86_64

    - name: Download jboss eap 6.4
      get_url:
        url: https://s3-ap-southeast-1.amazonaws.com/sl1729/installable/jboss-eap-6.4.zip
        dest: /devops/jboss-eap-6.4.zip
        force: no

    - name: Unarchive jboss eap 6.4
      unarchive:
        src: /devops/jboss-eap-6.4.zip
        dest: /opt/
        creates: /opt/jboss-eap-6.4/
        remote_src: yes

    - name: Create symlink jboss
      file: src=/opt/jboss-eap-6.4/ dest=/opt/jboss state=link

    - name: Create user jboss
      user: name=jboss uid=1040

    - name: Jboss change owner for the jboss base folder
      file: path="{{item}}" owner=jboss group=jboss recurse=yes
      with_items:
        - /opt/jboss-eap-6.4/

    - name: Jboss change owner for the jboss symlink
      file: src=/opt/jboss-eap-6.4/ dest=/opt/jboss owner=jboss group=jboss follow=no state=link

    - name: Jboss add users
      shell: ./add-user.sh admin DummyAdmin@123
      args:
        chdir: /opt/jboss/bin
      become: yes
      become_user: jboss
      becomd_method: su

    - name: Update jboss conf for run as user
      replace:
        path: /opt/jboss/bin/init.d/jboss-as.conf
        regexp: '^# JBOSS_USER=jboss-as'
        replace: 'JBOSS_USER=jboss'

    - name: Update standalong conf for the memory settings
      replace:
        path: /opt/jboss/bin/standalone.conf
        regexp: 'JAVA_OPTS="-Xms1303m -Xmx1303m -XX:MaxPermSize=256m -Djava.net.preferIPv4Stack=true"'
        replace: 'JAVA_OPTS="-Xms512m -Xmx512m -XX:MaxPermSize=256m -Djava.net.preferIPv4Stack=true"'

    - name: Copy jboss-as-standalone.sh to /etc/init.d
      copy:
        src: ./files/jboss-as-standalone.service
        dest: /etc/systemd/system
        mode: 0755

    - name: Update jboss.bind.address to listen to all
      replace:
        path: /opt/jboss/standalone/configuration/standalone.xml
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Enable jboss-as-standalone.service
      systemd: enabled=yes name=jboss-as-standalone.service state=reloaded
